### ISSUE TITLE
Import Canoe Asset

### ISSUE THREAD

**Issue by jquerin** [jquerin/RavioliVR#2]
Add a canoe asset to the project. Let's try a few out, but the ideal case would be one that is translucent.

**Comment by jquerin** [comment]
Well, the asset store seems to only have one canoe for free and it is like a traditional Native American canoe. Will have to look further into this.

**Comment by aaronding88** [comment]
Per Sunday session, this has been completed, and we'll mark it as complete once it's done

**Comment by jquerin** [comment]
note that the current asset will be placeholder for purposes of progression. A unique asset will most likely be custom built at a later point

**Comment by jquerin** [comment]
Fixed in c7d54bbb64817a6e2cfe9fdd2afc2d9f4ae3232c
